services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    env_file: ".env"
    networks:
      - default
    depends_on:
      - postgres
    ports:
    - "3001:3001"

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
    ports:
    - "3000:3000"
    networks:
      - default

  postgres:
    container_name: myfinance-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-myfinance_db}
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres:/data/postgres
    networks:
      - default
      
volumes:
  postgres:

networks:
  default:
